## Numpy Section

####  Question 1: Matrix Slicing and Submatrix Extraction

 ##### Create a 6×6 matrix with values from 0 to 35. Extract the central 4×4 submatrix.

In [13]:
import numpy as np

In [14]:
arr=np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [18]:
center=arr[1:5,1:5]
center

array([[ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28]])

#### Question 2: Percentile-Based Filtering

##### Generate a random 1D array of 20 elements. Replace all values below the 25th percentile with zero.

In [23]:
arr1=np.random.randn(20)
arr1

array([-0.67873699,  0.06272865, -0.01463175,  0.19030898,  0.07610128,
       -0.30367487, -0.14627984,  0.92638008, -0.23309056,  1.09758086,
        1.04766935, -0.28786121, -3.22289452,  0.69802616,  0.37884463,
       -0.73716731,  1.03393054,  0.48927411, -0.51174271, -1.27695105])

In [ ]:
q25=np.percentile(arr1,25)    
arr1[arr1<q25]=0
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

#### Question 3: Min-Max Normalization

##### Given an array of integers, normalize all values between 0 and 1 using min-max normalization

In [34]:
import numpy as np

In [38]:
data=np.random.randint(10,100,size=12)
norm=(data-np.min(data))/(np.max(data)-np.min(data))
print("Original:", data)
print("Normalized:", norm)

Original: [28 66 61 57 79 81 20 83 70 91 20 11]
Normalized: [0.2125 0.6875 0.625  0.575  0.85   0.875  0.1125 0.9    0.7375 1.
 0.1125 0.    ]


#### Question 4: 3D Array Stacking

##### Stack two random matrices of shape (4,3) and (4,3) along a new third dimension.

In [46]:
a=np.random.randn(4,3)
b=np.random.randn(4,3)
stacked=np.stack([a,b],axis=2)
print("Shape of stacked array:", stacked.shape)

Shape of stacked array: (4, 3, 2)


In [53]:
print("First element:\n", stacked[:, :, 0])

First element:
 [[ 0.55235016 -0.22939546  1.91537613]
 [ 0.18978703  0.16734222  0.96034852]
 [ 1.29283726  0.3232773  -1.13811713]
 [-0.56061527 -1.40841222  0.44473128]]


In [51]:
 stacked?

Type:        ndarray
String form:
[[[ 0.55235016 -0.44829177]
           [-0.22939546  1.12558969]
           [ 1.91537613 -0.96602104]]
           
           [[ 0.18978 <...> 20512176]]
           
           [[-0.56061527  1.10443279]
           [-1.40841222  0.88052047]
           [ 0.44473128  0.06632709]]]
Length:      4
File:        c:\users\user 10\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an a

####  Question 5: Unique Value Frequency Count

##### For a random array of integers, count unique values and their frequency efficiently.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1, 10, size=50)
values, counts = np.unique(arr, return_counts=True)
frequency_dict = {int(val): int(cnt) for val, cnt in zip(values, counts)}
print("Unique values and frequencies:")
print(frequency_dict)

Unique values and frequencies:
{1: 8, 2: 5, 3: 5, 4: 8, 5: 7, 6: 3, 7: 7, 8: 4, 9: 3}


In [4]:
arr = np.random.randint(1, 10, size=50)
values, counts = np.unique(arr, return_counts=True)
frequency_dict = dict(zip(values, counts))
print("Unique values and frequencies:")
print(frequency_dict)

Unique values and frequencies:
{np.int32(1): np.int64(3), np.int32(2): np.int64(2), np.int32(3): np.int64(6), np.int32(4): np.int64(10), np.int32(5): np.int64(9), np.int32(6): np.int64(9), np.int32(7): np.int64(3), np.int32(8): np.int64(3), np.int32(9): np.int64(5)}
