Q1: Create Array

Create a NumPy array with values from 1 to 10

Q2: Even Numbers

Create an array of even numbers from 2 to 20

🧩 Q3: Zeros Matrix

Create a 3×3 matrix of zeros

🧩 Q4: Reshape (IMPORTANT 🔥)

Convert this array into shape (2,3):

[1,2,3,4,5,6]
🧩 Q5: Find Shape

Given:

arr = np.array([[1,2,3],[4,5,6]])

👉 Find:

shape
number of dimensions
🧩 Q6: Indexing

From the same array:
👉 Extract value 5

🧩 Q7: Slicing

👉 Extract second column from:

[[1,2,3],
 [4,5,6]]
🧩 Q8: Sum

Find total sum of:

[10,20,30,40]
🧩 Q9: Axis Concept 🔥

For:

[[1,2,3],
 [4,5,6]]

👉 Find:

Row-wise sum
Column-wise sum
🧩 Q10: Max Index

Find index of maximum value:

[10, 50, 30, 20]

In [2]:
import numpy as np

In [3]:
# Q1: Create Array-Create a NumPy array with values from 1 to 10
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Q2: Even Numbers-Create an array of even numbers from 2 to 20
a=np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
#  Q3: Zeros Matrix-Create a 3×3 matrix of zeros
b=np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
# Q4: Reshape--Convert this array into shape (2,3):[1,2,3,4,5,6]
c=np.array([1,2,3,4,5,6]).reshape(2,3)
c

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# Q5: Find Shape-Given:arr = np.array([[1,2,3],[4,5,6]])-Shape,no.of.dimensions
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
d.shape

(2, 3)

In [13]:
d.ndim

2

In [14]:
# Q6: Indexing-From the same array:Extract value 5
print(d[1,1])

5


In [18]:
# Q7: Slicing Extract second column 
print(d[1:])
print(d[:,1])

[[4 5 6]]
[2 5]


In [19]:
# Q8: Sum-Find total sum of:[10,20,30,40]
e=np.sum([10,20,30,40])
e

np.int64(100)

In [22]:
# Q9: Axis Concept-For:[[1,2,3],[4,5,6]]Find:Row-wise sum,Column-wise sum
f=np.array([[1,2,3],[4,5,6]])
print(f.sum(axis=0))#column
print(f.sum(axis=1))#row

[5 7 9]
[ 6 15]


In [23]:
# Q10-Max Index:Find index of maximum value:[10, 50, 30, 20]
g=np.argmax([10,50,30,20])
g

np.int64(1)

🧩 NumPy Practice Set (Next 10)
🧩 Q11: Create Ones Matrix

Create a 4×2 matrix filled with ones

🧩 Q12: Full Value Array

Create a 3×3 matrix filled with value 9

🧩 Q13: Range with Step

Create an array from 5 to 50 with step 5

🧩 Q14: Linspace

Create 5 evenly spaced values between 0 and 1

🧩 Q15: Flatten

Convert this into a 1D array:

[[1,2],
 [3,4]]
🧩 Q16: Reshape Trick 🔥

Convert:

np.arange(1,13)

into shape (3, -1)

👉 What will be final shape?

🧩 Q17: Element-wise Operation

Add 10 to every element:

[1,2,3,4]
🧩 Q18: Condition (VERY IMPORTANT 🔥)

From:

[5, 12, 7, 20, 3]

👉 Get elements greater than 10

🧩 Q19: Min & Max

Find:

minimum value
maximum value
[8, 3, 15, 1, 9]
🧩 Q20: Sort

Sort this array:

[12, 4, 7, 1, 9]

In [24]:
# Q11: Create Ones Matrix:Create a 4×2 matrix filled with ones
h=np.ones((4,2))
h

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Q12: Full Value Array:Create a 3×3 matrix filled with value 9
i=np.full((3,3),9)
i

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [29]:
# Q13: Range with Step-Create an array from 5 to 50 with step 5
j=np.arange(5,51,5)
j

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
# Q14: Linspace:Create 5 evenly spaced values between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [35]:
# Q15: Flatten:Convert this into a 1D array:[[1,2], [3,4]]
k=np.array([[1,2],[3,4]])
k.flatten()

array([1, 2, 3, 4])

In [38]:
# Q16: Reshape Trick:Convert:np.arange(1,13) into shape (3, -1)
l=np.arange(1,13).reshape(3,-1)
l.shape

(3, 4)

In [39]:
# Q17: Element-wise Operation:Add 10 to every element:[1,2,3,4]
m=np.array([1,2,3,4])
m+10

array([11, 12, 13, 14])

In [41]:
# Q18: Condition:From:[5, 12, 7, 20, 3]:Get elements greater than 10
n=np.array([5, 12, 7, 20, 3])
n[n>10]

array([12, 20])

In [43]:
# 19: Min & Max:Find:minimum value,maximum value:[8, 3, 15, 1, 9]
o=np.array([8,3,15,1,9])
print(o.min())
print(o.max())

1
15


In [45]:
# Q20: Sort:Sort this array:[12, 4, 7, 1, 9]
p=np.array([12, 4, 7, 1, 9])
np.sort(p)

array([ 1,  4,  7,  9, 12])

🧩 Q21: Identity Matrix

Create a 4×4 identity matrix

🧩 Q22: Reverse Array

Reverse this array:

[1,2,3,4,5]
🧩 Q23: Reshape to Column

Convert:

[10,20,30,40]

into a column matrix (4×1)

🧩 Q24: Find Indices 🔥

From:

[4, 15, 6, 22, 8]

👉 Find indices of elements greater than 10

🧩 Q25: Replace Values (IMPORTANT 🔥)

Replace all values less than 10 with 0:

[5, 12, 7, 20, 3]
🧩 Q26: Row-wise Mean

Find mean of each row:

[[1,2,3],
 [4,5,6]]
🧩 Q27: Column-wise Max

Find maximum of each column:

[[3,7,2],
 [8,1,5]]
🧩 Q28: Stack Arrays

Given:

a = [1,2,3]
b = [4,5,6]

👉 Stack them vertically

🧩 Q29: Unique Values

Find unique elements:

[1,2,2,3,4,4,5]
🧩 Q30: Clip Values 🔥

Limit values between 5 and 15:

[2, 8, 20, 4, 15]

In [47]:
# Q21: Identity Matrix:Create a 4×4 identity matrix
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
# Q22: Reverse Array:
brr=[1,2,3,4,5]
brr[::-1]

[5, 4, 3, 2, 1]

In [49]:
# Q23: Reshape to Column:Convert:[10,20,30,40] into a column matrix (4×1)
crr=np.array([10,20,30,40]).reshape(4,1)
crr

array([[10],
       [20],
       [30],
       [40]])

In [52]:
# Q24: Find Indices From:[4, 15, 6, 22, 8] Find indices of elements greater than 10
i=np.array([4, 15, 6, 22, 8])
np.where(i>10)

(array([1, 3]),)

In [54]:
# Q25: Replace Values:Replace all values less than 10 with 0:[5, 12, 7, 20, 3]
j=np.array([5,12,7,20,3])
j[j<10]=0
j

array([ 0, 12,  0, 20,  0])

In [55]:
# Q26: Row-wise Mean:Find mean of each row:
z=np.array([[1,2,3],[4,5,6]])
z.mean(axis=1)

array([2., 5.])

In [56]:
# Q27: Column-wise Max:Find maximum of each column:
m=np.array([[3,7,2],[8,1,5]])
m.max(axis=1)

array([7, 8])

In [59]:
# Q28: Stack Arrays:Given:a = [1,2,3] b = [4,5,6] Stack them vertically
a =np.array([1,2,3])
b =np.array( [4,5,6])
s=np.vstack((a,b))
s

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# Q29: Unique Values:Find unique elements:
u=np.array([1,2,2,3,4,4,5])
uni=np.unique(u)
uni

array([1, 2, 3, 4, 5])

In [64]:
# Q30: Clip Values:Limit values between 5 and 15:
c=np.array([2, 8, 20, 4, 15])
np.clip(c,5,15)

array([ 5,  8, 15,  5, 15])