## SECTION A: MULTIPLE CHOICE QUESTIONS

### MCQ 1: NumPy Array Operations

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
result=np.dot(a,b.T)
result.shape

(2, 2)

### MCQ 2: Pandas DataFrame Filtering

In [3]:
import pandas as pd
df = pd.DataFrame({
    'A': [10, 20, 30, 40],
    'B': [100, 200, 150, 120]
})
result = df[(df['A'] > 15) & (df['B'] < 200)]
print(len(result))

2


### MCQ 3: NumPy Broadcasting

In [4]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
b = np.array([10, 20, 30])             # Shape: (3,)
result = a + b

In [6]:
result #b

array([[11, 22, 33],
       [14, 25, 36]])

### MCQ 4: Pandas GroupBy and Aggregation

In [5]:
import pandas as pd
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Value': [10, 20, 30, 15, 25]
})
result = df.groupby('Category')['Value'].agg(['sum', 'mean'])
print(result.loc['A', 'mean'])

21.666666666666668


### MCQ 5: NumPy Array Manipulation

In [8]:
import numpy as np
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])
indices = np.argsort(arr)
sorted_arr = arr[indices]
print(sorted_arr[-2])

6


## SECTION B: CODING QUESTIONS

### Coding Question 1: Array Reshaping and Axis Operations

#### 1. Create a 1D array with values from 1 to 12

In [9]:
import numpy as np

#### 2. Reshape it into a 3x4 matrix

In [12]:
arr=np.arange(1,13).reshape(3,4)
print(f"Array shape:{arr}")

Array shape:[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### 3. Calculate the sum along axis 0 (column-wise)

In [15]:
sum=np.sum(arr,axis=0)
print(f"Sum along columns:{sum}")

Sum along columns:[15 18 21 24]


#### 4. Calculate the mean along axis 1 (row-wise)

In [16]:
mean=np.mean(arr,axis=1)
print(f"Mean along rows:{mean}")

Mean along rows:[ 2.5  6.5 10.5]


#### 5. Find the standard deviation of the entire array

In [17]:
std=np.std(arr)
print(f"Standard Deviation:{std}")

Standard Deviation:3.452052529534663


### Coding Question 2: NumPy Advanced Indexing and Masking

#### 1. Create a 2D array of shape (5, 4) with random integers between 1 and 100

In [27]:
arr=np.random.randint(1,101, size=(5,4))
print(f"Array shape:{arr}")

Array shape:[[ 83  39  10  23]
 [  2   4  23  20]
 [100  68  54  46]
 [ 93  90  58  21]
 [ 68  55  10  31]]


#### 2. Create a boolean mask to identify elements greater than 50

In [30]:
mask=arr>50
print(f"Mask:{mask}")

Mask:[[ True False False False]
 [False False False False]
 [ True  True  True False]
 [ True  True  True False]
 [ True  True False False]]


#### 3. Replace all elements greater than 50 with their squared values

In [97]:
modified = arr.copy()
modified[mask] = modified[mask] ** 2
modified[mask]

array([ 6889, 10000,  4624,  2916,  8649,  8100,  3364,  4624,  3025],
      dtype=int32)

#### 4. Replace all elements less than or equal to 50 with 0

In [98]:
modified[~mask]=0

In [99]:
modified

array([[ 6889,     0,     0,     0],
       [    0,     0,     0,     0],
       [10000,  4624,  2916,     0],
       [ 8649,  8100,  3364,     0],
       [ 4624,  3025,     0,     0]], dtype=int32)

#### 5. Calculate what percentage of elements were greater than 50 in the original array

In [53]:
total=arr.size
count=mask.sum()
percentage=(count/total)*100
print(f"Percentage:{percentage}")

Percentage:45.0


#### 6. Print the modified array and the percentage

In [100]:
print(modified)
print(percentage)

[[ 6889     0     0     0]
 [    0     0     0     0]
 [10000  4624  2916     0]
 [ 8649  8100  3364     0]
 [ 4624  3025     0     0]]
45.0


### Coding Question 3: Pandas DataFrame Merging and Joining

In [65]:
import pandas as pd
df1 = pd.DataFrame({
'emp_id': [101,102,103,104,105],
'emp_name':["Ganesh","Ram","Moorthi","Vishnu","Sameer"],
'sales_amount':[1000,2000,3000,4000,5000]
 })

In [74]:
df2 = pd.DataFrame({
'emp_id': [101,102,103,104,105],
'bonus_rate':[10,20,30,40,50]

 })

#### 1. Merge the two DataFrames on `emp_id`

In [90]:
merged=pd.merge(df1,df2,on='emp_id')

In [114]:
merged

,emp_id,emp_name,sales_amount,bonus_rate,bonus_amount
0,101,Ganesh,1000,10,10000
1,102,Ram,2000,20,40000
2,103,Moorthi,3000,30,90000
3,104,Vishnu,4000,40,160000
4,105,Sameer,5000,50,250000


#### 2. Create a new column `bonus_amount` = `sales_amount * bonus_rate`

In [91]:
merged['bonus_amount']=merged['sales_amount']*merged[ 'bonus_rate']

#### 3. Sort the result by `bonus_amount` in descending order

In [92]:
merged.sort_values(by='bonus_amount', ascending=False)

,emp_id,emp_name,sales_amount,bonus_rate,bonus_amount
4,105,Sameer,5000,50,250000
3,104,Vishnu,4000,40,160000
2,103,Moorthi,3000,30,90000
1,102,Ram,2000,20,40000
0,101,Ganesh,1000,10,10000


#### 4. Display employees with bonus_amount > 500

In [94]:
max_bonus=merged[merged['bonus_amount']>500]
max_bonus

,emp_id,emp_name,sales_amount,bonus_rate,bonus_amount
0,101,Ganesh,1000,10,10000
1,102,Ram,2000,20,40000
2,103,Moorthi,3000,30,90000
3,104,Vishnu,4000,40,160000
4,105,Sameer,5000,50,250000


#### 5. Calculate the total bonus for all employees

In [96]:
total=merged['bonus_amount'].sum()
total

np.int64(550000)

### Coding Question 4: Pandas DataFrame Filtering and Aggregation 

#### 1. Create the DataFrame with sample data

In [3]:
import pandas as pd
df = pd.DataFrame({
'product_id': [101,102,103,104,105,106,107,108,109,110],
'product_name':['Ganesh','Ram','Moorthi','Vishnu','Sameer','bala','arun','vicky','yogi','vetri'],
'category': ['Electronics','Electronics','Clothing','Food','Food',
                 'Clothing','Electronics','Clothing','Food','Electronics'],
'Price':[800,1200,300,50,100,400,900,200,80,1500],
'quantity_sold':[30,15,50,80,75,55,60,24,22,10]
 })

In [4]:
df

,product_id,product_name,category,Price,quantity_sold
0,101,Ganesh,Electronics,800,30
1,102,Ram,Electronics,1200,15
2,103,Moorthi,Clothing,300,50
3,104,Vishnu,Food,50,80
4,105,Sameer,Food,100,75
5,106,bala,Clothing,400,55
6,107,arun,Electronics,900,60
7,108,vicky,Clothing,200,24
8,109,yogi,Food,80,22
9,110,vetri,Electronics,1500,10


#### 2. Filter products where `price > 500` and `quantity_sold > 20`

In [5]:
Filtered= df[(df['Price'] > 500) & (df['quantity_sold'] > 20)]

#### 3. Group by `category` and calculate:
   - Total revenue per category (price × quantity_sold)
   - Average price per category
   - Total quantity sold per category

In [6]:
df['Total_Revenue']=df['Price']*df['quantity_sold'] 

In [7]:
df1=df.groupby('category').agg({'Total_Revenue':'sum','Price':'mean','quantity_sold':'sum'})

In [8]:
df

,product_id,product_name,category,Price,quantity_sold,Total_Revenue
0,101,Ganesh,Electronics,800,30,24000
1,102,Ram,Electronics,1200,15,18000
2,103,Moorthi,Clothing,300,50,15000
3,104,Vishnu,Food,50,80,4000
4,105,Sameer,Food,100,75,7500
5,106,bala,Clothing,400,55,22000
6,107,arun,Electronics,900,60,54000
7,108,vicky,Clothing,200,24,4800
8,109,yogi,Food,80,22,1760
9,110,vetri,Electronics,1500,10,15000


 #### 4.Find the top 3 products by total revenue

In [9]:
top3=df.groupby('product_id')['Total_Revenue'].sum().nlargest(3).reset_index()

In [10]:
top3

,product_id,Total_Revenue
0,107,54000
1,101,24000
2,106,22000


#### 5.Calculate the percentage contribution of each category to overall revenue

In [11]:
overall=df['Total_Revenue'].sum()

In [12]:
percentage=(df1['Total_Revenue']/overall)*100

In [13]:
percentage.reset_index()

,category,Total_Revenue
0,Clothing,25.171625
1,Electronics,66.843310
2,Food,7.985066


In [15]:
# Step 6: Calculate percentage contribution of each category to overall revenue
category_revenue = df.groupby('category')['Total_Revenue'].sum()
total_revenue = category_revenue.sum()
revenue_percentage = (category_revenue / total_revenue * 100).round(2)
 
print("\n\nRevenue Contribution by Category:")
for category, percentage in revenue_percentage.items():
    revenue = category_revenue[category]
    print(f"{category}: ${revenue:,.0f} ({percentage}%)")



Revenue Contribution by Category:
Clothing: $41,800 (25.17%)
Electronics: $111,000 (66.84%)
Food: $13,260 (7.99%)


### Coding Question 5: NumPy Operations with Pandas Integration 

#### 1. Creates a NumPy array of shape (10, 5) with random values between 0 and 100

In [6]:
import numpy as np
import pandas as pd

In [7]:
arr=np.random.rand(10,5)*100

In [8]:
arr

array([[80.32091461, 33.73978252, 79.08694694, 29.48272354, 38.55944658],
       [46.61109589, 34.68468777, 65.31826879, 45.13373188, 30.05828756],
       [72.33670189, 82.74080217, 22.53643584, 69.51765258, 64.04497827],
       [80.35868129, 83.67436899, 10.43746438,  5.03840929, 75.46561612],
       [54.96192324, 15.11322821, 15.2877227 , 35.70638583, 59.3478606 ],
       [32.90492816, 31.03599893, 12.6369755 , 23.94007662, 14.79496357],
       [52.69494027, 16.6535166 , 30.27739773, 39.42380575, 44.27678483],
       [70.96665266, 63.06594777,  5.23990468, 32.96398168, 44.97304687],
       [16.33779654, 53.78311104, 54.20486904, 82.62168381, 63.88876649],
       [13.77285495, 13.87163399,  7.86200472, 60.19608158, 53.4008404 ]])

#### 2. Converts this array to a pandas DataFrame with columns named `A`, `B`, `C`, `D`, `E`

In [9]:
df=pd.DataFrame(arr,columns=['A','B','C','D','E'])

In [10]:
df

,A,B,C,D,E
0,80.320915,33.739783,79.086947,29.482724,38.559447
1,46.611096,34.684688,65.318269,45.133732,30.058288
2,72.336702,82.740802,22.536436,69.517653,64.044978
3,80.358681,83.674369,10.437464,5.038409,75.465616
4,54.961923,15.113228,15.287723,35.706386,59.347861
5,32.904928,31.035999,12.636975,23.940077,14.794964
6,52.694940,16.653517,30.277398,39.423806,44.276785
7,70.966653,63.065948,5.239905,32.963982,44.973047
8,16.337797,53.783111,54.204869,82.621684,63.888766
9,13.772855,13.871634,7.862005,60.196082,53.400840


### 3. Perform the following operations:

#### Calculate the correlation matrix between all columns

In [11]:
corr_matrix=df.corr() #matrix
corr_matrix

,A,B,C,D,E
A,1.000000,0.502980,0.049965,-0.558693,0.190356
B,0.502980,1.000000,-0.129475,-0.024275,0.490095
C,0.049965,-0.129475,1.000000,0.224051,-0.233783
D,-0.558693,-0.024275,0.224051,1.000000,0.212573
E,0.190356,0.490095,-0.233783,0.212573,1.000000


#### Identify which two columns have the highest correlation

In [12]:
corr_no_diag = corr_matrix.where(~np.eye(len(corr_matrix), dtype=bool)) #remove diagonals
corr_no_diag

,A,B,C,D,E
A,NaN,0.502980,0.049965,-0.558693,0.190356
B,0.502980,NaN,-0.129475,-0.024275,0.490095
C,0.049965,-0.129475,NaN,0.224051,-0.233783
D,-0.558693,-0.024275,0.224051,NaN,0.212573
E,0.190356,0.490095,-0.233783,0.212573,NaN


In [13]:
max_value=corr_no_diag.max()
max_value.reset_index() 

,index,0
0,A,0.502980
1,B,0.502980
2,C,0.224051
3,D,0.224051
4,E,0.490095


In [14]:
max_value.max()

0.5029800138836087

In [15]:
col1, col2 = corr_no_diag.stack().idxmax()
col1, col2

('A', 'B')

#### Create a new column `Average` = mean of all numeric columns

In [16]:
df['Average']=df.mean(axis=1)
df

,A,B,C,D,E,Average
0,80.320915,33.739783,79.086947,29.482724,38.559447,52.237963
1,46.611096,34.684688,65.318269,45.133732,30.058288,44.361214
2,72.336702,82.740802,22.536436,69.517653,64.044978,62.235314
3,80.358681,83.674369,10.437464,5.038409,75.465616,50.994908
4,54.961923,15.113228,15.287723,35.706386,59.347861,36.083424
5,32.904928,31.035999,12.636975,23.940077,14.794964,23.062589
6,52.694940,16.653517,30.277398,39.423806,44.276785,36.665289
7,70.966653,63.065948,5.239905,32.963982,44.973047,43.441907
8,16.337797,53.783111,54.204869,82.621684,63.888766,54.167245
9,13.772855,13.871634,7.862005,60.196082,53.400840,29.820683


#### Normalize all columns (subtract mean, divide by std dev)

In [12]:
norm=(df-df.mean()/df.std())
norm

,A,B,C,D,E,Average
0,29.502001,72.111115,72.285230,64.770634,79.026961,61.249966
1,91.549122,13.281107,93.412760,95.032479,77.848354,71.935543
2,71.930655,64.448137,5.287186,-1.492741,16.987077,29.142841
3,50.230136,22.752402,28.154278,35.600545,97.901956,44.638642
4,52.424112,23.629379,0.765694,83.882867,67.810198,43.413228
5,59.238616,75.270748,26.555326,85.114370,92.972025,65.540995
6,31.699347,74.760239,22.909515,39.827090,43.205778,40.191172
7,91.935657,6.785111,62.338433,83.860193,18.780082,50.450673
8,21.167831,74.871077,85.282701,1.848331,7.016476,35.748061
9,2.014317,39.737003,94.916345,91.665686,53.746685,54.126785


#### Find rows where the `Average` is in the top 20% (highest 2 rows out of 10)

In [13]:
top20=df.nlargest(2,'Average')

In [14]:
top20

,A,B,C,D,E,Average
1,93.296372,14.992352,94.799419,96.655588,79.588967,75.866540
5,60.985866,76.981993,27.941985,86.737479,94.712639,69.471992
