## Day 1 – NumPy Basics: 10 Questions
## Question 1

### Write a NumPy program to:
#### Create a 1D array of integers from 5 to 14 (inclusive).
#### Print the array, its `dtype`, `ndim`, and `shape`.

In [2]:
import numpy as np

In [11]:
arr=np.arange(5,15)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
arr.dtype

dtype('int64')

In [13]:
arr.ndim

1

In [14]:
arr.shape

(10,)

In [15]:
print(arr,arr.dtype,arr.ndim,arr.shape)

[ 5  6  7  8  9 10 11 12 13 14] int64 1 (10,)


## Question 2
### Convert the list `[2, 4, 6, 8, 10]` to a NumPy array and:
#### Multiply all elements by 3.
#### Subtract 2 from each element.`
#### Print the final array

In [17]:
lst=[2,4,6,8,10]
arr=np.array(lst)
arr

array([ 2,  4,  6,  8, 10])

In [18]:
arr=arr*3
arr

array([ 6, 12, 18, 24, 30])

In [19]:
arr=arr-2
arr

array([ 4, 10, 16, 22, 28])

## Question 3
### Create a 2D NumPy array of shape `(3, 3)` containing numbers from 1 to 9.
#### Print the array.
#### Print its `size` and `shape`.

In [22]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print(arr.size,arr.shape)

9 (3, 3)


## Question 4
### Create a 1D array of 10 zeros and then:
#### Set the 1st, 5th, and 10th elements to 7.
#### Print the array.


In [27]:
arr=np.zeros(10,dtype=int)
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
arr[0]=arr[4]=arr[6]=7

In [30]:
arr

array([7, 0, 0, 0, 7, 0, 7, 0, 0, 0])

## Question 5
### Use `np.arange` to create an array of odd numbers from 1 to 19.
#### Print the array and its sum.


In [32]:
arr=np.arange(1,20,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [34]:
arr.sum()

np.int64(100)

## Question 6
### Create a 4×4 identity matrix using NumPy and print it.

In [37]:
arr=np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Question 7
### Using NumPy random module, generate a 1D array of 6 random integers between 0 and 20.
#### Use a fixed seed of 10.
#### Print the array, the maximum value, and the index of the maximum.

In [39]:
np.random.seed(10)

In [41]:
arr=np.random.randint(0,21,size=6)
arr

array([17,  8,  9,  0, 10,  8], dtype=int32)

In [43]:
arr.max()

np.int32(17)

In [45]:
arr.argmax()

np.int64(0)

## Question 8
### Given `a = np.array([1, 3, 5, 7])` and `b = np.array([2, 4, 6, 8])`, compute and print: `a + b``a * b``b - a``b / a`

In [46]:
a=np.array([1,3,5,7])
b=np.array([2,4,6,8])

In [50]:
a+b

array([ 3,  7, 11, 15])

In [52]:
b-a

array([1, 1, 1, 1])

In [53]:
a*b

array([ 2, 12, 30, 56])

In [54]:
b/a

array([2.        , 1.33333333, 1.2       , 1.14285714])

## Question 9
### Create a 2D array of shape `(2, 5)` with values from 10 to 19.
#### Print the first row.
#### Print the second column of this array.

In [56]:
arr=np.arange(10,20).reshape(2,5)
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
arr[0,:]

array([10, 11, 12, 13, 14])

In [59]:
arr[:,1]

array([11, 16])

## Question 10
### Use `np.linspace` to create 15 values between 0 and 5 (inclusive).
#### Print the array, its first 3 elements, and last 3 elements.

In [3]:
arr=np.linspace(0,5,15)
arr

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

In [4]:
arr[:3]

array([0.        , 0.35714286, 0.71428571])

In [5]:
arr[-3:]

array([4.28571429, 4.64285714, 5.        ])

In [6]:
np.linspace?

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001F08768BEC0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\_core\function_base.py
Docstring:      
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop