# Day 3 – NumPy Reshape, Aggregation, Broadcasting: 10 Questions
## Question 1
### Create a 1D array of numbers from 1 to 15.
#### Reshape it to 3×5.
#### Print the reshaped array and its shape.


In [2]:
import numpy as np

In [4]:
arr=np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
arr.shape

(3, 5)

## Question 2
### Create a 3×3 array with values from 2 to 10 (inclusive).
#### Compute and print the overall sum, mean, max, and min.

In [7]:
arr=np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [10]:
arr.mean()

np.float64(6.0)

In [11]:
arr.sum()

np.int64(54)

In [12]:
arr.max()

np.int64(10)

In [13]:
arr.min()

np.int64(2)

## Question 3
### Create a 4×4 array with values from 0 to 15.
#### Compute the sum along rows.
#### Compute the sum along columns.

In [15]:
arr=np.arange(0,16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
arr.sum(axis=1)

array([ 6, 22, 38, 54])

In [18]:
arr.sum(axis=0)

array([24, 28, 32, 36])

## Question 4
### Create a 2×3 array `A = [[1, 2, 3], [4, 5, 6]]` and a 1D array `b = [10, 20, 30]`.
#### Use broadcasting to add `b` to each row of `A`.
#### Print the result.

In [22]:
A=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])

In [23]:
A+b

array([[11, 22, 33],
       [14, 25, 36]])

## Question 5
### Create a column vector `c = [[1], [2], [3]]` and row vector `[10, 20, 30, 40]`.
#### Use broadcasting to create a 3×4 matrix `M = c + row_vector`.
#### Print `M`.

In [24]:
c=np.array([[1],[2],[3]])
d=np.array([10,20,30,40])

In [26]:
M=c+d
M

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43]])

## Question 6
### Create a 2×6 array and reshape it into a 3D array of shape `(2, 2, 3)`.
#### Print the original and reshaped arrays.

In [28]:
arr=np.arange(12).reshape(2,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
arr.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## Question 7
### Create a 2×5 array with values from 0 to 9.
#### Flatten it back to 1D using `ravel` and `flatten`.
#### Print both and note the difference (view vs copy conceptually).

In [31]:
arr=np.arange(0,10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
r=arr.ravel()
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
f=arr.flatten()
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question 8
### Create an array of shape `(5, 3)` with random integers.
####  Compute mean of each column.
####  Compute mean of each row.

In [44]:
np.random.seed(1)
arr1=np.random.randint(1,20,size=(5,3))
arr1

array([[ 6, 12, 13],
       [ 9, 10, 12],
       [ 6, 16,  1],
       [17,  2, 13],
       [ 8, 14,  7]], dtype=int32)

In [45]:
np.random.seed(2)
arr2=np.random.randint(1,20,size=(5,3))
arr2

array([[ 9, 16, 14],
       [ 9, 12, 19],
       [12,  9,  8],
       [ 3, 18, 12],
       [16,  6,  8]], dtype=int32)

In [46]:
arr1.mean(axis=0)

array([ 9.2, 10.8,  9.2])

In [47]:
arr1.mean(axis=1)

array([10.33333333, 10.33333333,  7.66666667, 10.66666667,  9.66666667])

In [48]:
arr2.mean(axis=0)

array([ 9.8, 12.2, 12.2])

In [49]:
arr2.mean(axis=1)

array([13.        , 13.33333333,  9.66666667, 11.        , 10.        ])

## Question 9
### Create a 1D array with elements `[1, 2, 2, 3, 3, 3, 4, 4]`.
#### Find unique values and their counts.

In [50]:
arr=np.array([1,2,2,3,3,3,4,4])
arr

array([1, 2, 2, 3, 3, 3, 4, 4])

In [52]:
vals,counts=np.unique(arr,return_counts=True)
vals,counts

(array([1, 2, 3, 4]), array([1, 2, 3, 2]))

## Question 10
### Create a 1D array of 5 elements and a scalar value 10.
### Use broadcasting to add the scalar to the array.
#### Multiply the array by 2.
#### Print the results.

In [53]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [57]:
scalar=10
arr+scalar

array([11, 12, 13, 14, 15])

In [58]:
arr*2

array([ 2,  4,  6,  8, 10])