# Day 2 – NumPy Indexing & Slicing: 10 Questions

## Question 1
### Create a 1D NumPy array with values 0 to 19.
#### Print elements from index 4 to 10 (inclusive).
#### Print every third element from the array.


In [1]:
import numpy as np

In [4]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
arr[4:11]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[::3]

array([ 0,  3,  6,  9, 12, 15, 18])

## Question 2
### Create a 3×4 array with values from 0 to 11.
#### Print the second row.
#### Print the last column.
#### Print the element at row index 2, column index 1.

In [10]:
arr=np.arange(0,12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
arr[1,:]

array([4, 5, 6, 7])

In [16]:
arr[:,3]

array([ 3,  7, 11])

In [18]:
arr[2,1]

np.int64(9)

## Question 3
### Create a 1D array from 1 to 12.
#### Extract elements at indices `[0, 3, 5, 7, 11]` using fancy indexing.
#### Print the result.

In [3]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
idx=[0,3,5,7,11]
print(arr[idx])

[ 1  4  6  8 12]


## Question 4
### Create a 4×4 array with values from 1 to 16.
#### Print the 2×2 subarray from the middle.
#### Print the diagonal elements.

In [7]:
arr=np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [9]:
arr[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [13]:
np.diag(arr)

array([ 1,  6, 11, 16])

In [2]:
np.diag?

Signature:       np.diag(v, k=0)
Call signature:  np.diag(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function diag at 0x00000157038E28E0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\lib\_twodim_base_impl.py
Docstring:      
Extract a diagonal or construct a diagonal array.

See the more detailed documentation for ``numpy.diagonal`` if you use this
function to extract a diagonal and wish to write to the resulting array;
whether it returns a copy or a view depends on what version of numpy you
are using.

Parameters
----------
v : array_like
    If `v` is a 2-D array, return a copy of its `k`-th diagonal.
    If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
    diagonal.
k : int, optional
    Diagonal in question. The default is 0. Use `k>0` for diagonals
    above the main diagonal, and `k<0` for diagonals below the main
    diagonal.

Returns
-------
out : ndarray
    The extracted diagonal or constructed diagonal

## Question 5
### Create a 1D array with values from 10 to 19.
#### Reverse the array using slicing.
#### Reverse the array using `np.flip`.

In [14]:
arr=np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [17]:
np.flip(arr)

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [3]:
np.flip?

Signature:       np.flip(m, axis=None)
Call signature:  np.flip(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function flip at 0x000001570396D9E0>
File:            c:\users\user 10\anaconda3\lib\site-packages\numpy\lib\_function_base_impl.py
Docstring:      
Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

.. versionadded:: 1.12.0

Parameters
----------
m : array_like
    Input array.
axis : None or int or tuple of ints, optional
     Axis or axes along which to flip over. The default,
     axis=None, will flip over all of the axes of the input array.
     If axis is negative it counts from the last to the first axis.

     If axis is a tuple of ints, flipping is performed on all of the axes
     specified in the tuple.

     .. versionchanged:: 1.15.0
        None and tuples of axes are supported

Returns
-------
out : array_like
    A view of `m` with the entries of ax

## Question 6
### Create a 5×5 array with values from 0 to 24.
#### Print all elements in the first two rows.
#### Print all elements in the last two columns.

In [20]:
arr=np.arange(0,25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr[:2,:]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
arr[:,-2:]

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24]])

## Question 7
### Create a 3×3 array with values from 1 to 9.
#### Replace all elements greater than 5 with 0.
#### Print the modified array.

In [24]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr[arr>5]=0

In [26]:
arr

array([[1, 2, 3],
       [4, 5, 0],
       [0, 0, 0]])

## Question 8
### Create a 1D array of size 10 with random integers between 1 and 50.
#### Use boolean indexing to print all elements greater than 30.
#### Use boolean indexing to print all elements that are even.

In [4]:
np.random.seed?

Signature:      np.random.seed(seed=None)
Call signature: np.random.seed(*args, **kwargs)
Type:           cython_function_or_method
String form:    <cyfunction seed at 0x0000015703C7B6B0>
Docstring:     
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator

In [29]:
np.random.seed(1)
arr=np.random.randint(1,51,size=10)
arr

array([38, 44, 13,  9, 10, 12,  6, 16,  1, 17], dtype=int32)

In [30]:
arr[arr>30]

array([38, 44], dtype=int32)

In [31]:
arr[arr%2==0]

array([38, 44, 10, 12,  6, 16], dtype=int32)

## Question 9
### Create a 4×3 array with values from 1 to 12.
#### Print the first column as a 1D array.
#### Print the last row.

In [33]:
arr=np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
arr[:,0]

array([ 1,  4,  7, 10])

In [35]:
arr[-1,:]

array([10, 11, 12])

## Question 10
### Create a 1D array from 0 to 9.
#### Set elements at indices `[1, 3, 5, 7, 9]` to -1 using fancy indexing.
#### Print the final array.

In [37]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
idx=[1,3,5,7,9]
arr[idx]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])